### ISSUE TITLE
Icons are tiny on HiDPI screen and not enough space for text

### ISSUE THREAD

**Issue by howff** [guanlisheng/wxsqliteplus#31]
The toolbar icons are tiny on a High DPI screen, and some of the text doesn't fit into the space (space too small, rather than font too big). Windows 10, 3840x2400, scaling=250%

You probably can't tell from this screenshot, but the icons should probably be double the size or more.

This also affects the Query output window - the row height is too small so none of the text can be read.

![image](https://github.com/user-attachments/assets/92f16088-7caf-40ea-a4fc-f78e9fa45eb4)

**Comment by guanlisheng** [comment]
thanks, @howff, I will take a look and upgrade these legacy icons. 
btw, what's your os?

**Comment by howff** [comment]
Windows 10. I think the problem is not the icons but some scaling factor issue in the gui toolkit (wx?) because it affects the rows of text too.

**Comment by guanlisheng** [comment]
can you help to verify v0.4.0 ?  https://github.com/guanlisheng/wxsqliteplus/releases/tag/v0.4.0

**Comment by howff** [comment]
All looks good now, thank you!
